import { Product, Review, Seller } from './types';

export const sellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Luna Looms',
    location: 'Portland, OR',
    bio: 'Textile artist weaving modern heirlooms with natural fibers and gentle palettes.',
  },
  {
    id: 'seller-2',
    name: 'Cedar & Clay',
    location: 'Santa Fe, NM',
    bio: 'Small-batch ceramics inspired by desert skies and the calm of slow living.',
  },
  {
    id: 'seller-3',
    name: 'Willow Workshop',
    location: 'Asheville, NC',
    bio: 'Woodworker crafting warm, functional pieces that age beautifully with use.',
  },
];

export const products: Product[] = [
  {
    id: 'product-1',
    sellerId: 'seller-1',
    name: 'Handwoven Wall Hanging',
    description: 'A textured statement piece woven with plant-dyed wool and linen.',
    category: 'Textiles',
    price: 120,
    imageUrl: 'https://images.unsplash.com/photo-1616627456172-16f66d5f2125?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/16f66d5f2125',
  },
  {
    id: 'product-2',
    sellerId: 'seller-1',
    name: 'Indigo Throw Blanket',
    description: 'Lightweight throw dyed with natural indigo, finished with hand-twisted fringe.',
    category: 'Textiles',
    price: 180,
    imageUrl: 'https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/89e068629265',
  },
  {
    id: 'product-3',
    sellerId: 'seller-1',
    name: 'Plant-Dyed Table Runner',
    description: 'Linen runner colored with marigold petals and soft iron modifiers.',
    category: 'Textiles',
    price: 75,
    imageUrl: 'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/361805f42e86',
  },
  {
    id: 'product-4',
    sellerId: 'seller-2',
    name: 'Stoneware Mug',
    description: 'Wheel-thrown mug with a satin glaze and carved thumb rest for daily rituals.',
    category: 'Ceramics',
    price: 38,
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/6b1558fcca3d',
  },
  {
    id: 'product-5',
    sellerId: 'seller-2',
    name: 'Desert Sunrise Vase',
    description: 'Tall vase with layered glazes reminiscent of warm canyon mornings.',
    category: 'Ceramics',
    price: 95,
    imageUrl: 'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/246f612d3b3d',
  },
  {
    id: 'product-6',
    sellerId: 'seller-2',
    name: 'Carved Incense Holder',
    description: 'Low-profile incense holder with hand-etched geometrics and ash catch.',
    category: 'Ceramics',
    price: 28,
    imageUrl: 'https://images.unsplash.com/photo-1612196808214-b7e239e5f60c?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/b7e239e5f60c',
  },
  {
    id: 'product-7',
    sellerId: 'seller-3',
    name: 'Carved Walnut Serving Board',
    description: 'Curved-edge board finished with food-safe oil for gatherings and grazing.',
    category: 'Woodwork',
    price: 110,
    imageUrl: 'https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/2ecf227e85b2',
  },
  {
    id: 'product-8',
    sellerId: 'seller-3',
    name: 'Copper and Wood Candle Holder',
    description: 'Mixed-material candle holder pairing warm walnut with brushed copper.',
    category: 'Woodwork',
    price: 45,
    imageUrl: 'https://images.unsplash.com/photo-1603006905393-c8d6f6e8f2f8?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/c8d6f6e8f2f8',
  },
  {
    id: 'product-9',
    sellerId: 'seller-3',
    name: 'Leather-Bound Sketchbook',
    description: 'Hand-stitched sketchbook with removable cotton pages and wrap closure.',
    category: 'Leatherwork',
    price: 68,
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=80',
    imageSourceUrl: 'https://unsplash.com/photos/044cdead277a',
  },
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    productId: 'product-1',
    authorName: 'Maya',
    rating: 5,
    comment: 'The weaving is exquisite and the colors are calming in person.',
    createdAt: '2024-02-03',
  },
  {
    id: 'review-2',
    productId: 'product-1',
    authorName: 'Theo',
    rating: 4,
    comment: 'Beautiful craftsmanship, shipped with thoughtful packaging.',
    createdAt: '2024-03-12',
  },
  {
    id: 'review-3',
    productId: 'product-2',
    authorName: 'Ivy',
    rating: 5,
    comment: 'Soft, breathable, and the indigo tone is just right.',
    createdAt: '2024-01-28',
  },
  {
    id: 'review-4',
    productId: 'product-2',
    authorName: 'Sam',
    rating: 4,
    comment: 'Perfect spring layer; would love a larger size option.',
    createdAt: '2024-04-18',
  },
  {
    id: 'review-5',
    productId: 'product-3',
    authorName: 'Ana',
    rating: 4,
    comment: 'Adds a soft pop of color to our dining table.',
    createdAt: '2024-02-22',
  },
  {
    id: 'review-6',
    productId: 'product-4',
    authorName: 'Jordan',
    rating: 5,
    comment: 'New favorite mug — comfortable handle and great weight.',
    createdAt: '2024-03-02',
  },
  {
    id: 'review-7',
    productId: 'product-4',
    authorName: 'Casey',
    rating: 4,
    comment: 'Glaze is gorgeous; would love a matching pitcher.',
    createdAt: '2024-03-19',
  },
  {
    id: 'review-8',
    productId: 'product-5',
    authorName: 'Zoe',
    rating: 5,
    comment: 'Statement piece that still feels timeless.',
    createdAt: '2024-04-05',
  },
  {
    id: 'review-9',
    productId: 'product-6',
    authorName: 'Omar',
    rating: 3,
    comment: 'Nice design but ash spreads more than expected.',
    createdAt: '2024-01-11',
  },
  {
    id: 'review-10',
    productId: 'product-7',
    authorName: 'Riley',
    rating: 5,
    comment: 'Beautiful grain and the shape is comfortable to hold.',
    createdAt: '2024-02-14',
  },
  {
    id: 'review-11',
    productId: 'product-8',
    authorName: 'Nina',
    rating: 4,
    comment: 'Warm glow and sturdy base, exactly what I wanted.',
    createdAt: '2024-04-01',
  },
  {
    id: 'review-12',
    productId: 'product-9',
    authorName: 'Alex',
    rating: 5,
    comment: 'Paper quality is great for ink and the leather smells amazing.',
    createdAt: '2024-03-30',
  },
];
